### ISSUE TITLE
service installation failure

### ISSUE THREAD

**Issue by k4nfr3** [nccgroup/WindowsMemPageDelta#1]
Hello, 
in console mode no issue but trying to install it as a service didn't work for me

C:\Temp\WindowsMemPageDelta-1.0.0>WindowsMemPageDelta.exe -s
Service
Error doing dispatch
Finished service

OS : Windows 10 : 1909 x64 with admin priv

Regards
k4nfr3

**Comment by olliencc** [comment]
Hey to install the service you need to run from an elevated command prompt the following:

you don't start with -s from the command line.. 

```REM -------------------------------------------
REM This is the installation
REM -------------------------------------------
REM Copy the Eventlog DLL to the Windows directory
copy NCCGroup-WMPD-EvtLog.dll c:\Windows\NCCGroup-WMPD-EvtLog.dll
REM Copy the Main Binary
copy WindowsMemPageDelta.exe c:\Windows\WindowsMemPageDelta.exe
REM Create the service
sc create NCCMemDelta displayname= "NCC Group Memory Delta" binpath= "\"c:\Windows\WindowsMemPageDelta.exe\" -s"
REM Start the service
net start NCCMemDelta```

**Comment by olliencc** [comment]
Just to say there is now an install.bat in the release
